version: "3.5"

services:
  db:
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./enviroments/postgre.env
    image: postgres:alpine3.17
    volumes:
    - ./sqlscripts/orders.sql:/docker-entrypoint-initdb.d/orders.sql

  nuts:
    container_name: nuts
    ports:
      - 4222:4222
      - "8222:8222"
    restart: always
    image: nats-streaming:0.25.4

