version: "3.5"

services:
  db:
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./enviroments/postgre.env
    image: postgres:alpine3.17
    volumes:
    - ./sqlscripts/orders.sql:/docker-entrypoint-initdb.d/taorderssk.sql

  nuts:
    container_name: nuts
    ports:
      - 4222:4222
    image: nats:2.7.0-alpine

